menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/sunchongsheng
    GitHub: https://github.com/pinggod
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# About Me
about_me:
    # Show/Hide about me section
    show: false
    portrait: /portrait.jpg
    description: Jimmy Rustle is a software engineer at a start-up applying Artificial Intelligence and Deep Learning to improving zombie intelligence. At work, Jimmy uses the open source distributed machine learning framework ZombieFlow to scale their training models into oblivion.

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Analytics
# google-analytics:
ga: UA-65933410-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
